### ISSUE TITLE
Missing turbolinks enableProgressBar

### ISSUE THREAD

**Issue by c0m3tx** [Shopify/turbograft#100]
I just switched from turbolinks to turbograft, but I'm unable to find how to enable the progress bar.

Any hint?

**Comment by patrickdonovan** [comment]
We don't include it the way they do but you can DIY with something like 

```
$(document).on 'page:fetch turbograft:remote:init', -> NProgress.start()
$(document).on 'page:load turbograft:remote:always', -> NProgress.stop()
```

**Comment by c0m3tx** [comment]
So there is no native way to get a percentage of the page load completion? I don't even know if there is in turbolinks, actually.

Thanks for your help, really appreciated.

**Comment by celsodantas** [comment]
Nope, there's nothing native. =)

Closing this now.
