### ISSUE TITLE
error handler often attempts to access an undefined object

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/turbograft#118]
I think this is happening in `TurboGraft.Remote#onError`.  Looks like the exceptions are caused by trying to do `@opts.fail?` when `@opts` is not defined.  I'm not sure how that's possible, given that `@opts` is a constructor assignment.

Shopify's bugsnag shows 18,500+ exceptions since May 26th, so I'm guessing it's related to @justinthec's https://github.com/Shopify/turbograft/commit/dafb3a7f2ee851b64a69c22086ddb6c3c9b9e00a changes.

**Comment by justinthec** [comment]
[Link to BugSnag Event Collection](https://bugsnag.com/shopify/shopify-js/errors/57473f3fbe3f29e6a6051bbc?filters%5Bevent.since%5D%5B%5D=30d)

**Comment by justinthec** [comment]
My PR was merged the [25th](https://github.com/Shopify/turbograft/pull/117#event-672188164) and Twine was bumped on core to use it on [May 26th](https://github.com/Shopify/shopify/pull/73153#event-673511459) so it's 100% related to my changes.

I'll take a look at this.

**Comment by GoodForOneFare** [comment]
Today, an `Uncaught TypeError: window.scrollTo is not a function` error appeared.  It's occurring in `Turbolinks#resetScrollPosition`.  

The kicker is that the error is from `window.scrollTo` not being present in Chrome.  That's crazy.  I've no idea if it's related to this issue, but it seems odd that two "things that should exist"... aren't.

**Comment by justinthec** [comment]
The `@opts.fail?` errors seem to have gone away.

**Comment by GoodForOneFare** [comment]
Fixed by dem fat arrows in https://github.com/Shopify/turbograft/pull/119/files.
