### ISSUE TITLE
Page refresh on error sometimes causes a null reference exception

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/turbograft#120]
When called from `TurboGraft.Remote#onError`:
* [Page#refresh](https://github.com/Shopify/turbograft/blob/master/lib/assets/javascripts/turbograft/page.coffee#L25) passes in a `null` url parameter to `TurboLinks#loadPage`.
* [TurboLinks#loadPage](https://github.com/Shopify/turbograft/blob/master/lib/assets/javascripts/turbograft/turbolinks.coffee#L128) then tries to fish out `url.absolute`, which doesn't go well

Bugsnag shows that this has been happening in various locations since `Dec 27th, 2015, 17:49:09 EDT` (I think that's as far back as the logs go).  If more Shopify context is required, I can raise an issue with Bugsnag links in the main repo.

**Comment by TheMallen** [comment]
This should be fixed now :)
