### ISSUE TITLE
Navigating from page with named assets to page with none should refresh

### ISSUE THREAD

**Issue by TheMallen** [Shopify/turbograft#147]
## Bug
When you navigate from a page that has named tracked assets to a page with none you end up keeping all the styles from the page that had them. In our case this means the login page ends up looking broken when a user's session expires unless we follow the workaround. (only in the bundle split branch)

Version:  `v0.4.1`
Workaround: Put a `data-turbolinks-track="true"` on any `link` or `head` asset in the page with no named assets. TG will see that the set of anonymous tracked elements has gone from 0 to 1 and cause a refresh.

## Proposed Solution
When TG goes from a page with tracked assets of any kind to a page with 0 tracked assets of any kind, it should force a refresh. I can think of no situations where you might actively want the current behaviour that aren't really bad ideas.

**Comment by qq99** [comment]
What about removing them from `<head>`?  Apologies if this is at odds with some other aspect

I agree with you that there's probably not many scenarios where you want the style rules to stay around, can't think of any particularly reasonable ones.

**Comment by TheMallen** [comment]
Right now we're taking a never remove stuff from head approach. We start to head back to the realm of a big crazy graph I fear if we start doing destructive changes.
