### ISSUE TITLE
X-XHR-Redirected-To is sometimes applied to the wrong response

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/turbograft#148]
**Context**
[xhr_headers#store_for_turbolinks](https://github.com/turbolinks/turbolinks-classic/blob/master/lib/turbolinks/xhr_headers.rb#L26) stores redirect info in `session[:_turbolinks_redirect_to]`.  [set_xhr_redirected_to](https://github.com/turbolinks/turbolinks-classic/blob/master/lib/turbolinks/xhr_headers.rb#L32) fishes out this information, and applies it to a response.

**Problem**
If the browser makes multiple requests during an operation, the redirect info is applied to the first processed request.

**Example**
* Tweak `cards/apple_pay_supported_card.rb#qualifies?` to always return `true`
* Open dev tools and view the _Network_ tab
* View your home feed
* Scroll down to the card, and **quickly** click the _Activate Apple Pay_ button
* Note that the browser sends up a few requests:
  * _admin/home/consume_cards_
  * _admin/home/register_card_enagement_
  * _admin/settings/apple_pay_activation_
* Click through the response headers and note that `X-XHR-Redirected-To` is assigned to whichever request returns first

/cc @TheMallen

**Comment by qq99** [comment]
good find!

**Comment by TheMallen** [comment]
At first glance it seems like we should be storing which response it should be for. I wonder if we can get away without adding any extra info to the session though.

**Comment by TheMallen** [comment]
I wonder if we could just not worry about adding the header. I think we can maybe just determine redirect stuff on the client? I'll investigate on monday.
