### ISSUE TITLE
tg-remote should reset scrolling when it receives a redirect response

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/turbograft#149]
**Example**
* Tweak cards/apple_pay_supported_card.rb#qualifies? to always return true
* Open dev tools and view the Network tab
* View your home feed
* Scroll down to the card, *wait 5 seconds* and click the Activate Apple Pay button
* Note that the document body is still scrolled, when it should be at the top of the payments section

**Comment by GoodForOneFare** [comment]
@TheMallen the scrappy fix to this is to just dump a scroll reset around [this line](https://github.com/Shopify/turbograft/blob/master/lib/assets/javascripts/turbograft/turbolinks.coffee#L305).  

Do you have bandwidth to find the non-scrappy version of the fix?

**Comment by TheMallen** [comment]
I think once `Turbograft.response` exists (#144) we can have a more generically semantic `isRedirect` method on it, and then it'll be easier to include the scroll reset in a meaningful place.

In general, I don't really think `updateBody` is the right place for reflecting the url / handling scroll, so we could maybe move that whole section out or rename updateBody. Anyway, I think it'll be an easy refactor once we have some of the open PRs in. I'd do the scrappy one for now I guess.

**Comment by TheMallen** [comment]
We're also currently reseting the scroll as an `onLoad` callback from within `fetch`. So we can roll up both into one concrete check when we do the refactor.

**Comment by TheMallen** [comment]
#162 fixes this :)
