### ISSUE TITLE
Turbohead may insert duplicate scripts and/or execute inline scripts early

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/turbograft#151]
With a slow connection, it's easy to fool Turbohead into doing pathological things :/  This may be two separate issues; feel free to split them up.

-----

**Environment setup**
* Point your Gemfile at a local version of Turbograft and `dev up`
* Alter `Turbohead#insertAssetTask` to include this debug statement:
```coffeescript
insertAssetTask = (activeDocument, newNode, name) ->
  (done) ->
    console.log("Turbohead::insertAssetTask - inserting", newNode.src)
```
* In Chrome dev tools to use _Disabled cache_ & _Regular 3G_

-----

**Reproducing the duplicate scripts bug**
* Open your dev console
* Go to Home
* Refresh the browser
* Quickly navigate to _Products_
* Wait for the `insertAssetTask` message to appear for `admin-vendors-others`
* Quickly navigate to _Transfers_

![shop 1 transfers shopify 2016-09-15 01-18-16](https://cloud.githubusercontent.com/assets/673655/18539109/978f9efe-7ae2-11e6-9324-bc07f22b7049.png)

-----

**Reproducing the early inline scripts bug**
* Open your dev console
* Go to Home
* Refresh the browser
* Quickly navigate to _Products_
* Wait for the `insertAssetTask - inserting index-0123456789.js` message to appear
* Quickly navigate to _Orders_
* Note that inline scripts are executed as soon as _Orders_ HTML is received (before `index.js` has finished downloading)

![shop 1 orders shopify 2016-09-15 01-12-04](https://cloud.githubusercontent.com/assets/673655/18539018/caaf3cb4-7ae1-11e6-99d3-f0b544bc047b.png)

**Comment by justinthec** [comment]
😢 the inner machinations of turbograft are an enigma

**Comment by GoodForOneFare** [comment]
@justinthec do you ever sleep?  Patches welcome... :P

**Comment by edward** [comment]
> Point your Gemfile at a local version of Turbograft and dev up

Note that you can also do `bundle open turbograft` and your editor will open up the installed gem source for you to muck about in. You might have to set `$EDITOR` or `$BUNDLER_EDITOR` like so: `EDITOR=atom bundle open turbograft` or one of the many other ways to set environment variables in your shell.
