### ISSUE TITLE
Enable on ios chrome

### ISSUE THREAD

**Issue by DrewMartin** [Shopify/turbograft#62]
We explicitly disable turbograft on chrome for ios ([here](https://github.com/Shopify/turbograft/blob/master/lib/assets/javascripts/turbograft/turbolinks.coffee#L22-L23)) because [that's what turbolinks does](https://github.com/rails/turbolinks/blob/e5670fe2caf333a991a4b0949f762ad3e7aa8611/lib/assets/javascripts/turbolinks.js.coffee#L526-L527). The issue where this was brought up was https://github.com/rails/turbolinks/issues/82.

I don't think this is the case any more. At least, experimenting with it on my iphone and looking at the values in chrome for ios, I'm not seeing the order issue that initially caused this. I think we might be able to remove the check.

Thoughts? @kristianpd @qq99 @patrickdonovan @nsimmons @pushrax @angelini 

This would fix https://github.com/Shopify/shopify/issues/29477

**Comment by DrewMartin** [comment]
To actually poke around at values I used [weinre](http://people.apache.org/~pmuellr/weinre/docs/latest/Running.html) to allow remote debugging

**Comment by qq99** [comment]
Interesting.  So you tried a modified version and it seems to work on iOS Chrome?  IMO, the service using TG is going to be broken if it's not actually enabled, so it's a case of "broken either way", right?  I can't see it hurting to remove the disabling

**Comment by DrewMartin** [comment]
Chrome in particular worked fine. I think the problem that was brought up in rails/turbolinks no longer applies. The error that was causing the modal to not close is described in https://github.com/Shopify/turbograft/issues/63.

This one part worked with ios chrome, but I didn't come anywhere close to testing the whole admin in the browser. I figured it would be better to ask you guys who worked on turbograft whether you think other bugs to do with windows.history.state would still happen.

**Comment by qq99** [comment]
Yeah, I have no idea, but the other aspect is there are probably many other browsers where TG doesn't disable itself and presents bugs.  But, bugged if you do, bugged if you don't, right?

**Comment by DrewMartin** [comment]
Yeah. That's why I'm thinking we should maybe present something to them, kind of like the noscript page.

**Comment by DrewMartin** [comment]
But I guess for chrome we should enable it now. How much worse could it be than dying on partial refresh?
