### ISSUE TITLE
createDocument can be called when it's null

### ISSUE THREAD

**Issue by DrewMartin** [Shopify/turbograft#63]
[createDocument](https://github.com/Shopify/turbograft/blob/ef14332200c390efa166fd8f8dfa8c9ae68304f6/lib/assets/javascripts/turbograft/turbolinks.coffee#L294) can be called without being initialized first. If the browser doesn't support turbolinks for whatever reason ([here](https://github.com/Shopify/turbograft/blob/ef14332200c390efa166fd8f8dfa8c9ae68304f6/lib/assets/javascripts/turbograft/turbolinks.coffee#L350-L362)) we don't initialize createDocument. In Shopify we just assume that their browser supports it. We should either show something or provide backup behaviour for createDocument.

@kristianpd @qq99 @patrickdonovan @nsimmons @pushrax @angelini

**Comment by qq99** [comment]
Nice find :+1:

**Comment by qq99** [comment]
Sometimes, `createDocument` is an object:  https://exceptions.shopify.com/apps/536810a4b74f337c1a006d2f/errs/54de7ae6b74f334cdb001d75

**Comment by DrewMartin** [comment]
Gross.

**Comment by TheMallen** [comment]
Closing this as it's no longer relevant to the current implementation of TG. If there's a similar issue with the current build please feel free to open a new issue with updated links :)
