### ISSUE TITLE
TurboGraft.Remote @opts can be null

### ISSUE THREAD

**Issue by qq99** [Shopify/turbograft#69]
https://exceptions.shopify.com/apps/536810a4b74f337c1a006d2f/errs/54d3d6ceb74f333f4c00012d

```coffee
  onError: (ev) ->
    @opts.fail?()
```
Somehow, @opts can be null here...

**Comment by qq99** [comment]
I think it's this:

`xhr.addEventListener 'error', @onError`

Could be fixed by `@onError.bind(this)` or by using fat arrows in onSuccess and onError definitions

**Comment by TheMallen** [comment]
`remote#onError` is currently using fat arrows. I'll close this for now :)
