### ISSUE TITLE
resetScrollPosition can fail with Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by qq99** [Shopify/turbograft#70]
`Uncaught TypeError: object is not a function` when trying to call `scrollTo`
https://exceptions.shopify.com/apps/536810a4b74f337c1a006d2f/errs/54d3ed6cb74f333f4c001222

```coffee
  resetScrollPosition = ->
    if document.location.hash
      document.location.href = document.location.href
    else
      window.scrollTo 0, 0
```

```
HTTP_USER_AGENT 	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36
```

**Comment by TheMallen** [comment]
`window.scroll` and `window.scrollTo` are both identical and should be implemented in all the major browsers. I'm not sure how we could be breaking here, but if we want to be defensive we could simply do something like:

```
 scroll = window.scrollTo || window.scroll
 scroll 0, 0
```

**Comment by TheMallen** [comment]
I didn't see how old this is. We might not get these at all anymore. Checking bugsnag shows only a few `Object is not a function` exceptions and none are from this call.

**Comment by TheMallen** [comment]
Closed for now since it seems like this is now a nonissue
