### ISSUE TITLE
No-refresh (tg-static) and audio tag reset state

### ISSUE THREAD

**Issue by danieltamiosso** [Shopify/turbograft#87]
Hi guys, 

Do you know how we can handle with this following case?

1. Create a div with tg-static
2. Add an audio element inside this div
3. Visit a new page
4. The audio element keeps the same (not replaced, good)
5. But the audio player reset to the initial state (stop playing and back to the start)

**Comment by celsodantas** [comment]
your JS classes are probably getting re-initialized.

Closing as this is not an issue.
